version: '3.7'

services:
  go-app:
    container_name: go-app
    image: debayan/go-app:1.0.1
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    env_file:
      - .env  # Specify the correct path to your .env file

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}
